// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:9d316192-e301-4ff0-9aa6-2bb63115d659',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactawsphotos-hosting-mobilehub-1309242448',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2mlwbj3wrllfb.cloudfront.net',
    'aws_facebook_app_id': '1049578505155773',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '70cbd089587041b9aee0ecd2293dd2e6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c3f3b999-f55f-4d7b-a129-4131083b0d1c',
    'aws_project_name': 'ReactAwsPhotos-2018-04-20-11-45-22',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'reactawsphotos-mobilehub-1309242448',
    'aws_sign_in_enabled': 'enable',
}

export default awsmobile;
